### ISSUE TITLE
Non-free network services

### ISSUE THREAD

**Issue by julianfairfax** [tw-hx/fdroid#1]
Why does the Signal app description on F-Droid say it connects to non-free services, when the Signal server is open source software

**Comment by julianfairfax** [comment]
Is this since, NonFreeNet only considers the user freedom to choose the server? https://gitlab.com/fdroid/fdroiddata/-/issues/2695#note_995994903

**Comment by tw-hx** [comment]
Yeah, pretty much. Signal's server has recently included a small closed-source anti-spam blob, but the main reason is that you can't run your own server and federate like Matrix/XMPP.

**Comment by julianfairfax** [comment]
Oh yeah that's true as well. Not too big of deal imo but the inability to switch servers thing is correct. F-Droid's going to make it a separate category at some point though since that makes more sense

**Comment by julianfairfax** [comment]
GIPHY is also in the app it seems. Which is a non-free network service owned by Facebook. Can this be removed from Signal-FOSS? If not, it should count towards the non-free net anti-feature.

**Comment by tw-hx** [comment]
Signal does [proxy requests to GIPHY through their own server](https://signal.org/blog/signal-and-giphy-update/) for what it's worth, so your own IP address shouldn't make it as far as their owners (Facebook, although the UK is trying to make them sell it). I'm trying to keep patches as minimal as possible and focused on opening the client software binary.

It's not really possible to make Signal free of non-free services; many of Signal's own servers are physically hosted by the Google, Amazon and Microsoft clouds, and some logins are filtered through Google's ReCAPTCHA.
