### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by TPS** [tw-hx/fdroid#2]
@tw-hx There haven't been updates to this fork since May, but main has had updates continuously (last within 3 days, as of this post).  Is the CI broken?  I'd rather not risk kill-switch issues.

Cross-posted from https://www.twinhelix.com/cgi-bin/forum.pl/signalfoss/11

**Comment by TPS** [comment]
Got response there almost immediately:
> Sorry am away from my PC at the moment. Current build won't expire just yet, but sorry I know this means missing out on text formatting for now! Will pick up builds again in 3 weeks.
>
>Cheers

Will keep this open to track 'til then.

**Comment by tw-hx** [comment]
Have updated to 6.24.4.09-FOSS

**Comment by TPS** [comment]
@tw-hx Thanks very much! 🙇🏾‍♂️
